# Generated by Django 5.2.8 on 2025-11-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phonedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('pixel', 'pixel')], max_length=10)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('phone_price', models.IntegerField()),
                ('phone_image', models.ImageField(upload_to='phone_image/')),
            ],
        ),
    ]
